server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/dlcache/

spring.profiles.active: native


# avmoo-web-dev -> application-dev -> avmoo-web -> application -> error

#D:\dlcache\application.yml no application-native.yml
#spring.profiles.active: native读表示本地配置

#测试url都带.yml
#spring.cloud.config.server.default-label

#http://127.0.0.1:8888/dlcache/application OK

#http://127.0.0.1:8888/dlcache/application-native.yml OK
#http://127.0.0.1:8888/dlcache/application.yml 406

#http://127.0.0.1:8888/dlcache/avmooweb-native.yml OK
#http://127.0.0.1:8888/dlcache/avmooweb-native OK
#http://127.0.0.1:8888/dlcache/avmooweb OK