server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/dlcache/

spring.profiles.active: native

#http://127.0.0.1:8888/dlcache/application
#D:\dlcache\application.yml no application-native.yml